export const INVENTORY_CATEGORIES = [
  { id: 'toestellen', label: 'Toestellen en groot materiaal' },
  { id: 'ballen', label: 'Ballen' },
  { id: 'slagmateriaal', label: 'Handgereedschap / slagmateriaal' },
  { id: 'markering', label: 'Afbaken- en markeringsmateriaal' },
  { id: 'diversen', label: 'Diversen' }
];

const iconItem = (
  id,
  nameNl,
  category,
  color,
  allowedVenueKinds = ['indoor', 'outdoor'],
  imageKey = category
) => ({
  id,
  nameNl,
  category,
  renderMode: 'icon',
  width: 5,
  height: 5,
  color,
  imageKey,
  allowedVenueKinds
});

const footprintItem = (
  id,
  nameNl,
  category,
  color,
  width,
  height,
  allowedVenueKinds = ['indoor', 'outdoor'],
  imageKey = category
) => ({
  id,
  nameNl,
  category,
  renderMode: 'footprint',
  width,
  height,
  color,
  imageKey,
  allowedVenueKinds
});

export const INVENTORY_ITEMS = [
  footprintItem('bank', 'Bank 360 cm', 'toestellen', '#8d6e63', 3.6, 0.26, ['indoor'], 'bench'),
  footprintItem('zweedse-bank', 'Bank 300 cm', 'toestellen', '#6d4c41', 3, 0.26, ['indoor'], 'bench'),
  footprintItem('kleine-mat', 'Kleine mat', 'toestellen', '#e76f51', 1.5, 1, ['indoor'], 'mat'),
  footprintItem('turnmat', 'Turnmat 150 x 100', 'toestellen', '#f28482', 1.5, 1, ['indoor'], 'mat'),
  footprintItem('dikke-mat', 'Dikke mat', 'toestellen', '#e5989b', 3, 2, ['indoor'], 'mat'),
  footprintItem('landingsmat', 'Landingsmat', 'toestellen', '#ffb4a2', 4, 3, ['indoor'], 'mat'),
  footprintItem('turnkast', 'Turnkast', 'toestellen', '#b08968', 1.5, 0.85, ['indoor'], 'box'),
  footprintItem('bok', 'Bok', 'toestellen', '#a98467', 1.2, 0.45, ['indoor'], 'vault'),
  footprintItem('plint', 'Plint', 'toestellen', '#9c6644', 1.2, 0.5, ['indoor'], 'box'),
  footprintItem('springplank', 'Springplank', 'toestellen', '#ddb892', 1.2, 0.6, ['indoor'], 'board'),
  footprintItem('minitrampoline', 'Minitrampoline', 'toestellen', '#cb997e', 1.25, 1.25, ['indoor'], 'trampoline'),
  footprintItem('kastdeel', 'Kastdeel', 'toestellen', '#7f5539', 0.9, 0.5, ['indoor'], 'box'),
  footprintItem('klimtouw', 'Klimtouw', 'toestellen', '#a68a64', 0.3, 0.3, ['indoor'], 'rope'),
  footprintItem('ringen', 'Ringen', 'toestellen', '#a5a58d', 0.8, 0.8, ['indoor'], 'rings'),
  footprintItem('trapeze', 'Trapeze', 'toestellen', '#6b705c', 1, 0.35, ['indoor'], 'bar'),
  footprintItem('wandrek', 'Wandrek', 'toestellen', '#588157', 0.35, 2.5, ['indoor'], 'ladder'),
  footprintItem('rekstok', 'Rekstok', 'toestellen', '#3a5a40', 2.4, 0.4, ['indoor'], 'bar'),
  footprintItem('handbaldoel', 'Handbaldoel', 'toestellen', '#1d3557', 3, 2, ['indoor'], 'goal'),
  footprintItem('voetbaldoel-klein', 'Klein voetbaldoel', 'toestellen', '#457b9d', 2, 1, ['indoor', 'outdoor'], 'goal'),
  footprintItem('volleybalnet', 'Volleybalnet', 'toestellen', '#4895ef', 9.5, 1, ['indoor'], 'net'),
  footprintItem('badmintonnet', 'Badmintonnet', 'toestellen', '#4cc9f0', 6.1, 0.9, ['indoor'], 'net'),
  iconItem('basketbal', 'Basketbal', 'ballen', '#ff8f3d', ['indoor', 'outdoor'], 'ball'),
  iconItem('volleybal', 'Volleybal', 'ballen', '#59c3c3', ['indoor', 'outdoor'], 'ball'),
  iconItem('zaalvoetbal', 'Zaalvoetbal', 'ballen', '#3d5a80', ['indoor'], 'ball'),
  iconItem('buitenvoetbal', 'Buitenvoetbal', 'ballen', '#3d5a80', ['outdoor'], 'ball'),
  iconItem('handbal', 'Handbal', 'ballen', '#f4a261', ['indoor'], 'ball'),
  iconItem('korfbal', 'Korfbal', 'ballen', '#e9c46a', ['indoor', 'outdoor'], 'ball'),
  iconItem('rugbybal', 'Rugbybal', 'ballen', '#7f5539', ['outdoor'], 'oval-ball'),
  iconItem('hockeybal', 'Hockeybal (no-bounce)', 'ballen', '#264653', ['indoor', 'outdoor'], 'ball'),
  iconItem('gatenbal', 'Gatenbal', 'ballen', '#8ecae6', ['indoor', 'outdoor'], 'ring'),
  iconItem('tennisbal', 'Tennisbal', 'ballen', '#b5e48c', ['indoor', 'outdoor'], 'ball'),
  iconItem('tafeltennisbal', 'Tafeltennisbal', 'ballen', '#fefae0', ['indoor'], 'ball'),
  iconItem('softbal', 'Softbal', 'ballen', '#f28482', ['indoor', 'outdoor'], 'ball'),
  iconItem('foambal', 'Foambal', 'ballen', '#f6bd60', ['indoor', 'outdoor'], 'ball'),
  iconItem('speelbal', 'Speelbal', 'ballen', '#90be6d', ['indoor', 'outdoor'], 'ball'),
  iconItem('medicinebal', 'Medicinebal', 'ballen', '#6d597a', ['indoor'], 'ball'),
  iconItem('binnenstootkogel', 'Binnenstootkogel', 'ballen', '#6c757d', ['indoor'], 'ball'),
  iconItem('frisbee', 'Frisbee', 'ballen', '#2a9d8f', ['indoor', 'outdoor'], 'disc'),
  iconItem('springtouw', 'Springtouw', 'ballen', '#a8dadc', ['indoor', 'outdoor'], 'rope'),
  iconItem('springtouwtje', 'Springtouwtje', 'ballen', '#457b9d', ['indoor', 'outdoor'], 'rope'),
  footprintItem('stok-1m', 'Stok (1 meter)', 'ballen', '#adb5bd', 1, 0.03, ['indoor', 'outdoor'], 'stick'),
  footprintItem('trektouw', 'Trektouw', 'ballen', '#8d99ae', 10, 0.05, ['indoor', 'outdoor'], 'rope'),
  iconItem('hoepels', 'Hoepels', 'ballen', '#e76f51', ['indoor', 'outdoor'], 'ring'),
  iconItem('pittenzakjes', 'Pittenzakjes', 'ballen', '#bc4749', ['indoor', 'outdoor'], 'bag'),
  iconItem('kunststof-spelblokken', 'Kunststof spelblokken', 'ballen', '#4361ee', ['indoor', 'outdoor'], 'blocks'),
  iconItem('bouncebalset', 'Bouncebalset', 'ballen', '#ffb703', ['indoor', 'outdoor'], 'ball'),
  iconItem('beachbalset', 'Beachbalset', 'ballen', '#ffafcc', ['indoor', 'outdoor'], 'ball'),
  iconItem('werpringen', 'Werpringen', 'ballen', '#cdb4db', ['indoor', 'outdoor'], 'ring'),
  iconItem('jongleermateriaal', 'Jongleermateriaal', 'ballen', '#caffbf', ['indoor', 'outdoor'], 'juggle'),
  iconItem('partijlint', 'Partijlint', 'ballen', '#ff006e', ['indoor', 'outdoor'], 'bib'),
  iconItem('pilon', 'Pilon', 'ballen', '#fb8500', ['indoor', 'outdoor'], 'cone'),
  footprintItem('tijdelijke-belijning', 'Tijdelijke belijning', 'ballen', '#6a994e', 8, 0.08, ['indoor', 'outdoor'], 'tape'),
  iconItem('unihockeystick', 'Unihockeystick', 'slagmateriaal', '#1d3557', ['indoor'], 'stick'),
  iconItem('slagknuppel', 'Slagknuppel', 'slagmateriaal', '#b08968', ['indoor', 'outdoor'], 'stick'),
  footprintItem('slagplank', 'Slagplank', 'slagmateriaal', '#9c6644', 1.1, 0.3, ['indoor', 'outdoor'], 'board'),
  iconItem('estafettestokje', 'Estafettestokje', 'slagmateriaal', '#2a9d8f', ['indoor', 'outdoor'], 'stick'),
  iconItem('badmintonracket', 'Badmintonracket', 'slagmateriaal', '#577590', ['indoor'], 'racket'),
  iconItem('tennisracket', 'Tennisracket', 'slagmateriaal', '#277da1', ['indoor', 'outdoor'], 'racket'),
  iconItem('squashracket', 'Squashracket', 'slagmateriaal', '#4d908e', ['indoor'], 'racket'),
  iconItem('tafeltennisbat', 'Tafeltennisbat', 'slagmateriaal', '#43aa8b', ['indoor'], 'paddle'),
  iconItem('markeringsbol', 'Afbaken-/markeringsbol', 'markering', '#ff8800', ['indoor', 'outdoor'], 'marker'),
  iconItem('honken', 'Honken', 'markering', '#8338ec', ['indoor', 'outdoor'], 'base'),
  iconItem('markeerschijf', 'Markeerschijf', 'markering', '#3a86ff', ['indoor', 'outdoor'], 'disc'),
  iconItem('shuttles', 'Shuttles', 'diversen', '#f1faee', ['indoor'], 'shuttle'),
  footprintItem('toverkoord', 'Toverkoord', 'diversen', '#5e60ce', 6, 0.04, ['indoor', 'outdoor'], 'rope'),
  footprintItem('elastische-band', 'Elastische band', 'diversen', '#80ed99', 2.5, 0.05, ['indoor', 'outdoor'], 'rope'),
  footprintItem('hoogspringkoord', 'Hoogspringkoord', 'diversen', '#48bfe3', 4, 0.04, ['indoor', 'outdoor'], 'rope'),
  iconItem('zandloperset', 'Zandloperset', 'diversen', '#e5989b', ['indoor'], 'timer'),
  iconItem('stopwatch', 'Stopwatch', 'diversen', '#495057', ['indoor', 'outdoor'], 'timer'),
  footprintItem('meetlint', 'Meetlint', 'diversen', '#588157', 20, 0.05, ['indoor', 'outdoor'], 'tape'),
  footprintItem('scoreboard', 'Scoreboard', 'diversen', '#344e41', 0.6, 0.45, ['indoor', 'outdoor'], 'scoreboard'),
  iconItem('ballenpomp', 'Ballenpomp', 'diversen', '#6c757d', ['indoor', 'outdoor'], 'pump'),
  footprintItem('ballenwagen', 'Ballenwagen', 'diversen', '#6d6875', 1, 0.7, ['indoor'], 'cart'),
  footprintItem('opbergbox', 'Opbergboxen / materiaalkast', 'diversen', '#7f5539', 1.2, 0.5, ['indoor'], 'cabinet'),
  footprintItem('berging-hoepels', 'Berging hoepels', 'diversen', '#b56576', 0.9, 0.9, ['indoor'], 'rack'),
  footprintItem('whiteboard', 'Whiteboard', 'diversen', '#ced4da', 1.5, 0.6, ['indoor'], 'whiteboard'),
  footprintItem('magnesiumbak', 'Magnesiumbak', 'diversen', '#adb5bd', 0.6, 0.4, ['indoor'], 'tray'),
  iconItem('handfluit', 'Handfluit', 'diversen', '#ef476f', ['indoor', 'outdoor'], 'whistle')
];

export const inventoryLookup = Object.fromEntries(INVENTORY_ITEMS.map((item) => [item.id, item]));
